services:
    server:
        build:
            dockerfile: Dockerfile
            context: ./backend
        ports:
          - 8000:8000
        networks:
            - default
    client:
        build: 
            dockerfile: Dockerfile
            context: ./frontend
        ports:
          - 8501:8501
        networks:
            - default
        depends_on:
            - server

networks:
  default:
    external: true
    name: pond